name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate Renovate configuration file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.11
        with:
          pattern: "default.json"
